version: "3.8"

services:
  # MongoDB Service
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017" # Expose MongoDB for access

  # Combined Server-side (Node.js) and Client-side (Angular served by NGINX)
  app:
    build:
      context: . # Points to the root directory where the combined Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose Node.js API on port 3000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/chatappDB

volumes:
  mongodb-data:
